# syntax=docker/dockerfile:1
FROM python:3.10.10

WORKDIR /traffic_comparator
RUN mkdir /traffic_comparator/traffic_comparator

# I might not have to copy all of this in, but I'm not positive how much I can take out.
# This can also probably be arranged to maximize overlap with the other dockerfile
COPY traffic_comparator /traffic_comparator/traffic_comparator/
COPY setup.py /traffic_comparator/
COPY cli.py /traffic_comparator/

RUN pip3 install --editable ".[data]"

COPY ResultsRepository.ipynb /traffic_comparator/

CMD jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
